name: Deploy React Vite App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configura Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Genera el build
      - name: Build project
        run: npm run build

      # 5️⃣ Publica en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # Si tu repo no es de usuario/organización sino un proyecto, descomenta la línea siguiente:
          # publish_branch: gh-pages
